### ISSUE TITLE
Could not build for android/arm64 on centos

### ISSUE THREAD

**Issue by sanguohot** [fyne-io/fyne-cross#109]
### Describe the bug:

`[root@sgh-aliyun ~]# cd /opt/sghproxy-src/
[root@sgh-aliyun sghproxy-src]# **fyne-cross android -app-id io.sgh.sghproxy -arch arm64 -env GOPROXY=https://goproxy.cn ./bin/client_gui/app**
[i] Target: android/arm64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /opt/sghproxy-src/fyne-cross/bin/android-arm64
[✓] "dist" dir cleaned: /opt/sghproxy-src/fyne-cross/dist/android-arm64
[✓] "temp" dir cleaned: /opt/sghproxy-src/fyne-cross/tmp/android-arm64
[i] Checking for go.mod: /opt/sghproxy-src/go.mod
[✓] go.mod found
[i] Packaging app...
go build -buildmode=c-shared -o /tmp/gomobile-work-510562669/lib/arm64-v8a/libsghproxy_src.so github.com/sanguohot/sghproxy/bin/client_gui/app failed: exit status 2
github.com/go-gl/glfw/v3.3/glfw
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:188:
./glfw/src/x11_platform.h:33:10: fatal error: '**X11/Xlib.h**' file not found
include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.

[✗] could not package the Fyne app: could not package the Fyne app: exit status 1
[root@sgh-aliyun sghproxy-src]# **find / -name Xlib.h -type f**
/var/lib/docker/overlay2/9188d701460892282e226416e697c44e62a4199e009264be8a64e43a5ad6ca09/diff/usr/include/X11/Xlib.h
**/usr/include/X11/Xlib.h**`

### Device and debug info (please complete the following information):

<summary>Device info</summary>
CentOS Linux 7 3.10.0-1127.13.1.el7.x86_64

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

go version go1.16.3 linux/amd64

fyne-cross version v1.1.4-0.20220402185543-7567bc0a81f9

fyne version v2.1.4

**Comment by lucor** [comment]
Could you try with the latest version of fyne-cross (v1.2.1) ?

**Comment by sanguohot** [comment]
> Could you try with the latest version of fyne-cross (v1.2.1) ?

Well, it was my fault to use a fork fyne lib with some breaking changed. Now it works, just close it. Thank you for your kind suggestion.
