### ISSUE TITLE
The README file can cause a problem in a project

### ISSUE THREAD

**Issue by metal3d** [fyne-io/fyne-cross#113]
That's a little problem but it may cause problems for beginners. The README file proposes to install the tool with:

```bash
go get -u github.com/fyne-io/fyne-cross
```

But calling this in a project with `go.mod` file will break.

Since Go 1.16, it's recommended to use:

```bash
go install github.com/fyne-io/fyne-cross@latest
```

For those who are running older version of Go:
```bash
GO111MODULE=on  go get -u github.com/fyne-io/fyne-cross
```

A change in the README could be a good idea IMHO.

**Comment by Bluebugs** [comment]
And done. Thanks for the report.
