### ISSUE TITLE
Does it support go 1.18

### ISSUE THREAD

**Issue by wunderbarb** [fyne-io/fyne-cross#117]
It seems not as it does not recognize `any`.
I tried on Linux to cross-compile for windows.   Go.mod required 1.18

**Comment by andydotxyz** [comment]
You can see at https://github.com/fyne-io/fyne-cross/pull/115 that the upgrade to Go 1.18 is in progress.
We were waiting for Fyne v2.2.0 release before updating everything. That is now out so it will probably move forward soon.

**Comment by lucor** [comment]
The next version v1.3.0 that will ship 1.18 is ready for testing via #119
