### ISSUE TITLE
Problem with `g++` command while building for windows

### ISSUE THREAD

**Issue by mhkarimi1383** [fyne-io/fyne-cross#124]
### Describe the bug:

While I want to build my project for windows I'm getting error below

```text
# github.com/webview/webview
g++: error: unrecognized command line option '-mthreads'; did you mean '-pthread'?
```

I think some version changes caused issue

### To Reproduce:
Steps to reproduce the behaviour:
1. run `fyne-cross windows -pull`
2. See error

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** ArchLinux
 - **Version:** Rolling
 - **Go version:** 1.18.3
 - **fyne-cross version:** v1.3.0
 - **Fyne version:** v2.2.3
 - **Docker Image:** fyneio/fyne-cross:1.3-base

<details><summary>Debug info</summary><br><pre>

</pre></details>

**Comment by Jacalz** [comment]
Does this also happen if you build something like https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo?

**Comment by mhkarimi1383** [comment]
> Does this also happen if you build something simple like https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo?

YES...!

**Comment by Jacalz** [comment]
Hmm. That’s weird. I was compiling just today without issues. Perhaps @lucor has some insight?

**Comment by mhkarimi1383** [comment]
> Hmm. That’s weird. I was compiling just today without issues. Perhaps @lucor has some insight?

Let me just try again maybe I'm doing wrong

**Comment by Jacalz** [comment]
Now wait a minute. That text there points to https://github.com/webview/webview which depends on Gtk and WebKitGtk on Linux (and seems to do something else on Windows). As Fyne doesn’t use it, I’m pretty sure that the regular Fyne demo should work just as expected.

**Comment by mhkarimi1383** [comment]
> Now wait a minute. That text there points to https://github.com/webview/webview which depends on Gtk and WebKitGtk on Linux (and seems to do something else on Windows). As Fyne doesn’t use it, I’m pretty sure that the regular Fyne demo should work just as expected.

Yes it works...

**Comment by mhkarimi1383** [comment]
What should I do to make my application work without webview?

**Comment by Jacalz** [comment]
Indeed. Your dependency uses CGo and require separate dependencies to work. I don’t know why this happens but I don’t think it is anything that we can do about it. What do you think? @lucor

**Comment by Jacalz** [comment]
Cool. I’ll close this then.
