### ISSUE TITLE
fyne-cross fails with fixuid error

### ISSUE THREAD

**Issue by tucuxi** [fyne-io/fyne-cross#128]
### Describe the bug:

Cross compiling github.com/tucuxi/metaballs for windows fails as follows: 
```
❯ fyne-cross windows
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/kds/go/src/fyne-cross/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /home/kds/go/src/fyne-cross/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /home/kds/go/src/fyne-cross/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /home/kds/go/src/fyne-cross/go.mod
[✓] go.mod found
[!] Default icon not found at "/home/kds/go/src/fyne-cross/Icon.png"
[✓] Created a placeholder icon using Fyne logo for testing purpose
fixuid: fixuid is not running as root, ensure that the following criteria are met:
        - fixuid binary is owned by root: 'chown root:root /path/to/fixuid'
        - fixuid binary has the setuid bit: 'chmod u+s /path/to/fixuid'
        - NoNewPrivileges is disabled in container security profile
        - volume containing fixuid binary does not have the 'nosuid' mount option
failed to resize tty, using default size
[✗] could not package the Fyne app: exit status 1
```
Docker is running fine otherwise with default settings.

### To Reproduce:
Steps to reproduce the behaviour:
1. `git clone https://github.com/tucuxi/metaballs`
2. `cd metaballs`
3. `fyne-cross windows`

### Device and debug info:
 - OS:  Arch Linux
 - Version: rolling, up to date as of 2020-09-08
 - Go version: go1.19 linux/amd64
 - fyne-cross version: v1.3.0
 - Fyne version: v2.2.3

**Comment by lucor** [comment]
Unable to reproduce on my linux box:
```
Status: Downloaded newer image for fyneio/fyne-cross:1.3-windows
[i] Building binary...
[✓] Binary: /tmp/test/metaballs/fyne-cross/bin/windows-amd64/metaballs.exe
[i] Packaging app...
[✓] Package: /tmp/test/metaballs/fyne-cross/dist/windows-amd64/metaballs.exe.zip
```
It could be related to your docker or volume setup, something like https://github.com/boxboat/fixuid/issues/9#issuecomment-373998801

**Comment by tucuxi** [comment]
Thanks for the hint. In line with security guidelines, `/var` was mounted with the `nosuid` option. Remounting `/var` with default options, I was able to build the executable. Root cause identified and out of scope for fyne-cross, except perhaps for an entry in the troubleshooting section. Closing the ticket with this result.
