### ISSUE TITLE
pull darwin image fail

### ISSUE THREAD

**Issue by jhaoheng** [fyne-io/fyne-cross#129]
### Describe the bug:
I use `fyne-cross darwin --pull` and got the issue below.
And go to docker hub `https://hub.docker.com/r/fyneio/fyne-cross/tags?page=1&name=darwin`
There is no darwin image over there.

```
$fyne-cross darwin --pull
[i] Target: darwin/amd64
[i] Checking for a newer version of the docker image: docker.io/fyneio/fyne-cross:1.3-darwin
[✗] could not pull the docker image: exit status 1
```

### To Reproduce:
1. Run cmd `fyne-cross darwin --pull`

### Device and debug info (please complete the following information):
```
[i] Target: darwin/amd64
[i] Checking for a newer version of the docker image: docker.io/fyneio/fyne-cross:1.3-darwin
[✗] could not pull the docker image: exit status 1
```

**Comment by Jacalz** [comment]
Look at the note a few lines below in the README: https://github.com/fyne-io/fyne-cross#fyne-cross

You need to build the Darwin image locally due to licensing issues from Apple.
