### ISSUE TITLE
fyne-cross doesn't normalize executable name

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne-cross#139]
### Describe the bug:
fyne package does normalize the executable name to fit in filesystem better, while fyne-cross does use the application name. This lead to inconsistency when building for darwin on darwin (as fyne-cross use fyne package in that case) and might likely cause bugs in some case.

For reference fyne package normalization function is here: https://github.com/fyne-io/fyne/blob/42fa9008fad15ae2ba5b52182865cfb18647fec3/cmd/fyne/internal/commands/package.go#L389

### To Reproduce:
Steps to reproduce the behaviour:
1. Create an app that has a name which does not match the module name.
2. Use fyne-cross to generate a package for darwin on darwin
3. Use fyne-cross to generate a package for darwin from another OS
4. Binary names differ inside the package

**Comment by Bluebugs** [comment]
Potential fix for this is to use more of fyne command in the container directly.

**Comment by lucor** [comment]
Fixed in `develop` via #143
