### ISSUE TITLE
macOS local build does not pass architecture

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne-cross#149]
### Describe the bug:
Irrespective of the architecture flag passed, a darwin build on a darwin computer will compile it for the current architecture.

### To Reproduce:
Steps to reproduce the behaviour:
1. go to an intel macOS
2. run `fyne-cross darwin -arch arm64 -app-id thingy`
3. run `file fyne-cross/dist/darwin-arm64/thingy.app/Contents/MacOS/thingy`

See
```
fyne-cross/dist/darwin-arm64/thingy.app/Contents/MacOS/thingy: Mach-O 64-bit executable x86_64
```

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** macOS (intel)
 - **Version:** Montery
 - **Go version:** 1.18.4
 - **fyne-cross version:** v1.3.0
 - **Fyne version:** v2.2.4

**Comment by Bluebugs** [comment]
This seems to be also the case the other way around when building for amd64 on an arm64. I will get: `/Users/administrator/BuilderSpace/nomad/fyne-cross/dist/darwin-amd64/Nomad.app/Contents/MacOS/nomad: Mach-O 64-bit executable arm64`

**Comment by Bluebugs** [comment]
This is actually fixed in the Apple M1 branch.

**Comment by Bluebugs** [comment]
The branch for Apple M1 has been landed in develop and fixes this issue.
