### ISSUE TITLE
Compiling for Windows doesn't set the Icon correctly

### ISSUE THREAD

**Issue by EinsKatze** [fyne-io/fyne-cross#155]
### Describe the bug:
When using fyne-cross to compile for Windows, the Icon specified only gets set for the File in the Explorer but does not show on the Application when running it.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a basic Fyne Application
2. Create a FyneApp.toml and specify an Icon (or specify the Icon in the fyne-cross command)

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** Windows 11
 - **Version:** 22H2
 - **Go version:** 1.19.2
 - **fyne-cross version:** 1.3.0
 - **Fyne version:** 2.3.0

**Comment by Bluebugs** [comment]
I think this is because we are not using `fyne build` to build the application, so we are missing some metadata being set. I should look into it in the coming days as I think it would be great to get all the metadata working with fyne-cross too.

**Comment by Bluebugs** [comment]
This is now fixed in develop.
