### ISSUE TITLE
Support full semver versions with -app-version flag

### ISSUE THREAD

**Issue by joshuar** [fyne-io/fyne-cross#210]
### Is your feature request related to a problem? Please describe:
I have an app using fyne where I'm following semver versioning. I also use goreleaser to run `fyne-cross` as needed. However, when I try to build a prerelease of my app, `fyne-cross` fails as it doesn't understand a semver version with a pre-release tag in it like `4.1.1-SNAPSHOT-fef3bae`. This breaks my build pipeline during development. I get the following error with the aforementioned version passed to `-app-version`:

```
invalid -appVersion parameter, integer and '.' characters only up to x.y.z
```

### Is it possible to construct a solution with the existing API?
While I could easily fake a `X.Y.Z` version in the pipeline, that may cause confusion with generated artifacts. It would be much nicer if `fyne-cross` just support **any** full semver version.

### Describe the solution you'd like to see:
Full support for semver versions (as per the semver spec) for `-app-version` flag.

**Comment by andydotxyz** [comment]
Unfortunately this may not be possible. Some platforms don't support semver and we have to use a combination that will work everywhere. For example windows is "X.Y.Z.P" where we use the version and build id to construct the version number. Therefore adding more info would be lost on some platforms which feels worse...

**Comment by joshuar** [comment]
Oh TIL. I might be misusing this flag then. I will rework my build pipeline. Thank you for the response! I will close this issue off.
