### ISSUE TITLE
Build for MacOS (arm64,amd64) not working

### ISSUE THREAD

**Issue by eschricker** [fyne-io/fyne-cross#232]
### Describe the bug:

The build for MacOS is not working with version 1.5.0.

I have tested with different SDK versions. 

The following error is shown:
```
flag provided but not defined: -w"
```
### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** Linux -->
 - **Target-OS:** MacOS
 - **Version:** Fedora 39
 - **Go version:** 1.21.
 - **fyne-cross version:** 1.5.0
 - **Fyne version:** 2.4.4

**Comment by Bluebugs** [comment]
Do you have any go flags at in your environment? Can you share the command line you are using?

**Comment by eschricker** [comment]
I have not set any go flags. 

The commands are:
```bash
fyne-cross darwin -arch=amd64 --macosx-sdk-path ${SDK_DIR} ./cmds/gui
fyne-cross darwin -arch=arm64 --macosx-sdk-path ${SDK_DIR} ./cmds/gui
```

SDK_DIR points to `MacOSX11.3.sdk`.

If fyne-cross is fixed to v1.4.0 it build succeeds.

**Comment by Bluebugs** [comment]
I am able to reproduce the problem. Will investigate.

**Comment by Bluebugs** [comment]
It seems this does not affect build on darwin host targeting darwin.
