### ISSUE TITLE
Linux Building Darwin Error

### ISSUE THREAD

**Issue by figuerom16** [fyne-io/fyne-cross#238]
### Describe the bug:
MacOS fails to compile for AMD64 and ARM64.
Is there a better SDK to use other than 12.3?
Windows and Linux have no issues.

### To Reproduce:
fyne-cross darwin -arch=amd64,arm64 --macosx-sdk-path /home/matt/Documents/go/MACSDKs/MacOSX12.3.sdk

### Example code:
https://gitlab.com/figuerom16/moxyspice 

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** Pop!_OS 22.04 LTS
 - **Go version:** 1.22.2
 - **fyne-cross version:** 1.5.0
 - **Fyne version:** 2.4.5

<summary>Debug info</summary>

[output.txt](https://github.com/fyne-io/fyne-cross/files/15033931/output.txt)

**Comment by Bluebugs** [comment]
Oh, I just realize, you are using 12.3 for MacOS SDK. I don't think this version is supported. @andydotxyz do you know if that version work with Fyne now?

**Comment by Bluebugs** [comment]
It is currently recommended to use 11.3.

**Comment by figuerom16** [comment]
I've tried using the 11.3 SDK.  Here is the generated output error.
[output_11.3.txt](https://github.com/fyne-io/fyne-cross/files/15138919/output_11.3.txt)

**Comment by Bluebugs** [comment]
Ah, you are also seeing the issue reported in #232. Looking into it at the moment.

**Comment by figuerom16** [comment]
Ah ok.  I'll close this since #232 covers this and I'll watch that issue.  Thanks.
