### ISSUE TITLE
Add FreeBSD on arm64 target

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne-cross#29]
Go 1.14 added support for building against the `arm64` target of FreeBSD (see https://golang.org/doc/go1.14#freebsd). Given that we now use Go 1.14, this should technically be possible to do. This would be a very addition given the recent increase and excitement in `arm64` over `amd64`.

**Comment by Jacalz** [comment]
I think this will require that we build our FreeBSD images against FreeBSD 12.x instead of 11.2.

**Comment by lucor** [comment]
Added in #37
