### ISSUE TITLE
Failing to cross-compile from linux to windows

### ISSUE THREAD

**Issue by Cookie04DE** [fyne-io/fyne-cross#30]
I am on linux debian and my linux version is 4.19.0-13-amd64.
My go version is go1.16beta1 linux/amd64.
The fyne-cross version is v1.0.0.
I have two modules, a lib and an app.
The lib's go mod:
```
module github.com/Cookie04DE/Lib

go 1.16

require fyne.io/fyne v1.4.3
```

The app's go mod:
```
module github.com/Cookie04DE/App

go 1.16

require (
	fyne.io/fyne v1.4.3
	github.com/Cookie04DE/Lib v0.0.0
	github.com/stretchr/testify v1.6.1 // indirect
	github.com/webview/webview v0.0.0-20210115112615-0f8224c31374
)

replace github.com/Cookie04DE/Lib => /absolute/path/to/Lib
```
I opened a terminal in the app's folder and executed the following command: ```fyne-cross windows .```.
I got the following output:
```
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "dist" dir cleaned: /absolute/path/to/App/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /absolute/path/to/App/fyne-cross/tmp/windows-amd64
[✓] "bin" dir cleaned: /absolute/path/to/App/fyne-cross/bin/windows-amd64
[i] Checking for go.mod: /absolute/path/to/App/go.mod
[✓] go.mod found
[i] Building binary...
go: github.com/Cookie04DE/Lib@v0.0.0: parsing /absolute/path/to/Lib/go.mod: open /absolute/path/to/Lib/go.mod: no such file or directory
[✗] exit status 1
```
The error message says that it can't find ```/absolute/path/to/Lib/go.mod```.
The file exists and when I execute ```cat /absolute/path/to/Lib/go.mod``` I get the correct output:
```
module github.com/Cookie04DE/Lib

go 1.16

require fyne.io/fyne v1.4.3
```

**Comment by Jacalz** [comment]
I think this is happening because of the replace you have in the module. Fyne-cross uses a docker container that contains a Linux distribution and your application sources, but it does not contain the path that you replaced it with (because the container is sandboxed from the rest of the system).

**Comment by Jacalz** [comment]
This could probably be solved by having fyne-cross parse the go module and copy in the replaced modules to the container, but it will be complicated and could be a possible source of security issues. Not sure off the back of my mind if fyne-cross copies over a vendor folder, but if it does, I would recommend doing the changes in your vendor folder instead.

**Comment by lucor** [comment]
In addition to @Jacalz 's comments, please also note that the current version of fyne-cross ships with go v1.14.x.

**Comment by Cookie04DE** [comment]
Vendoring solved my issue, thanks! There's a new problem however:
```
main.go:5:2: cannot find package "." in:
        /app/vendor/embed
```
This is probably because fyne-cross doesn't support go 1.16 yet. Should I make a new issue anyway?
