### ISSUE TITLE
Error cross-compiling to windows 386

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne-cross#47]
D:\project\mygosoft\src\riskExcel2021>fyne-cross windows -arch=386
[i] Target: windows/386
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-386
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-386
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\windows-386
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Building binary...
go: fyne.io/fyne/v2@v2.0.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.0.3.mod": dial tcp 172.217.24.17:443: connect: connection refused
[✗] exit status 1

**Comment by Jacalz** [comment]
Do you have an internet connection?

**Comment by xfengw** [comment]
yes



***@***.***
 
From: Jacob
Date: 2021-05-18 15:21
To: fyne-io/fyne-cross
CC: xfengw; Author
Subject: Re: [fyne-io/fyne-cross] dial tcp 172.217.24.17:443: connect: connection refused (#47)
Do you have an internet connection?
―

**Comment by xfengw** [comment]
GOPROXY=https://goproxy.o,direct

**Comment by lucor** [comment]
If you need a proxy it can be specified with the --env flag:

```
fyne-cross linux --env GOPROXY=<your_proxy>
```

Note: make sure you're using the latest version v1.1.0 since it fixes an issue (#35) about this

**Comment by xfengw** [comment]
D:\project\mygosoft\src\riskExcel2021>fyne-cross windows -arch=386 --env GOPROXY=https://goproxy.io
[i] Target: windows/386
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-386
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-386
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\windows-386
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Building binary...
# riskExcel2021
/usr/local/go/pkg/tool/linux_amd64/link: running i686-w64-mingw32-gcc failed: exit status 1
/tmp/go-link-826086927/000000.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

[✗] exit status 2
why？

**Comment by lucor** [comment]
It's hars to say without looking at your code. 
Anyway one possibility could be a `*.syso` library in your project that is linked during the linux cross-compilation.
Also make sure if you're using third-party libs that they support not Windows OSes.

**Comment by xfengw** [comment]
D:\project\mygosoft\src\riskExcel2021>fyne-cross windows -arch=amd64,386 --env GOPROXY=https://goproxy.io
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-amd64
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-amd64
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\windows-amd64
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Building binary...
# riskExcel2021
/usr/bin/x86_64-w64-mingw32-ld: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 1 lang: 409
[✓] Binary: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-amd64\riskExcel2021.exe
[i] Packaging app...
[✓] Package: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-amd64\riskExcel2021.exe.zip
[i] Target: windows/386
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-386
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-386
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\windows-386
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Building binary...
# riskExcel2021
/usr/local/go/pkg/tool/linux_amd64/link: running i686-w64-mingw32-gcc failed: exit status 1
/tmp/go-link-777420976/000000.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

[✗] exit status 2

D:\project\mygosoft\src\riskExcel2021>fyne-cross windows -arch=386 --env GOPROXY=https://goproxy.io
[i] Target: windows/386
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\windows-386
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\windows-386
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\windows-386
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Building binary...
# riskExcel2021
/usr/local/go/pkg/tool/linux_amd64/link: running i686-w64-mingw32-gcc failed: exit status 1
/tmp/go-link-864744859/000000.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

[✗] exit status 2



***@***.***
 
From: Luca Corbo
Date: 2021-05-19 02:24
To: fyne-io/fyne-cross
CC: xfengw; Author
Subject: Re: [fyne-io/fyne-cross] dial tcp 172.217.24.17:443: connect: connection refused (#47)
If you need a proxy it can be specified with the --env flag:
fyne-cross linux --env GOPROXY=<your_proxy>

Note: make sure you're using the latest version v1.1.0 since it fixes an issue (#35) about this

**Comment by andydotxyz** [comment]
Looking at it there seems to be a mix between windows and linux tools being used - don't you think @lucor ?
`/usr/local/go/pkg/tool/linux_amd64/link: running i686-w64-mingw32-gcc failed: exit status 1`
That's linux amd64 linker using the windows 64bit compiler...

**Comment by andydotxyz** [comment]
I wonder if it's worth removing the fyne_cross folder and starting again after the network troubles earlier?

**Comment by lucor** [comment]
> Looking at it there seems to be a mix between windows and linux tools being used - don't you think @lucor ?
> `/usr/local/go/pkg/tool/linux_amd64/link: running i686-w64-mingw32-gcc failed: exit status 1`
> That's linux amd64 linker using the windows 64bit compiler...

It should be the correct one `i686` is for cross-compiling targeting 386 arch. The rest of the name is related to the debian package...

> I wonder if it's worth removing the fyne_cross folder and starting again after the network troubles earlier?

fyne-cross should remove the temporary dirs at every run. To ensure also the go cache is not used:

```
fyne-cross windows -arch=386 --env GOPROXY=https://goproxy.io,direct --no-cache
```

@xfengw  can you please confirm that no third-party packages are used in your project ? Additionally, it would be great a link to the repo project or a minimal example (main.go + go.mod) that reproduces the issue.

**Comment by xfengw** [comment]
is ok

**Comment by andydotxyz** [comment]
> is ok

Does this mean that the issue is resolved?

**Comment by junmaqiang** [comment]
> GOPROXY=https://goproxy.o,direct


GOPROXY=https://goproxy.cn,direct
