### ISSUE TITLE
Unable to set FYNE_SCALE during build

### ISSUE THREAD

**Issue by xilefff** [fyne-io/fyne-cross#49]
Hi! 
Setting FYNE_SCALE is not working. The build target is Linux/ARM.

I'm building with:
`fyne-cross linux -arch=arm --env FYNE_SCALE=2.0`

Any ideas why this is happening? 

Thanks!

**Comment by lucor** [comment]
[FYNE_SCALE](https://developer.fyne.io/architecture/scaling) should be set on the host where the program is running not at build time.

Example: `FYNE_SCALE=2.0 <your_binary>`

**Comment by xilefff** [comment]
Working perfectly fine now, thank you!
