### ISSUE TITLE
Unable to pull darwin image

### ISSUE THREAD

**Issue by Nv7-GitHub** [fyne-io/fyne-cross#62]
When I try to build for `darwin`, I get
```
[✓] go.mod found
[i] Packaging app...
[i] Building binary...
Unable to find image 'fyneio/fyne-cross:1.1-darwin' locally
docker: Error response from daemon: manifest for fyneio/fyne-cross:1.1-darwin not found: manifest unknown: manifest unknown.
See 'docker run --help'.
[✗] exit status 125
```
Windows and Linux work though. Any ideas on how to fix?

**Comment by andydotxyz** [comment]
Due to Apple licensing issues you first have to call `fyne-cross darwin-image` and follow any instructions.
It will look for, or ask you to download, Apple's SDK which we are not allowed to distribute with fyne-cross.

**Comment by Jacalz** [comment]
See the https://github.com/fyne-io/fyne-cross#build-the-docker-image-for-osxdarwinapple-cross-compiling section for more details.

**Comment by Nv7-GitHub** [comment]
Thank you!
