### ISSUE TITLE
Reference to local file, compilation error

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne-cross#65]
PS D:\project\mygosoft\src\IpTools> fyne-cross windows -icon Icon.png -env GOPROXY=https://goproxy.io
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\IpTools\fyne-cross\bin\windows-amd64
[✓] "dist" dir cleaned: D:\project\mygosoft\src\IpTools\fyne-cross\dist\windows-amd64
[✓] "temp" dir cleaned: D:\project\mygosoft\src\IpTools\fyne-cross\tmp\windows-amd64
[i] Checking for go.mod: D:\project\mygosoft\src\IpTools\go.mod
[✓] go.mod found
[i] Building binary...
go: findDomainWhoisInfo@v0.0.0-00010101000000-000000000000 (replaced by ../findDomainWhoisInfo): reading /findDomainWhoisInfo/go.mod: open /findDomainWhoisInfo/go.mod: no such file or directory

**Comment by andydotxyz** [comment]
fyne-cross does not support referencing modules on the file system outside your project.
If you need to reference unreleased code then your best bet is probably to vendor it into the project (`go mod vendor`).

**Comment by Jacalz** [comment]
Closing per above comment. See https://github.com/fyne-io/fyne-cross/issues/30 for the same problem.
