### ISSUE TITLE
MAC compile to andriod  err

### ISSUE THREAD

**Issue by YinYongTao** [fyne-io/fyne-cross#68]
My Mac Info
![image](https://user-images.githubusercontent.com/26930834/135194498-a5b67af7-df92-48a5-9516-5d664a5ace51.png)

`func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))
	w.ShowAndRun()
}`

`fyne-cross android -app-id=a.b.c`

![image](https://user-images.githubusercontent.com/26930834/135195083-bce2fc64-d23d-406c-b7ba-8e8173d8a428.png)

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by andydotxyz** [comment]
This has been fixed in Fyne v2.1.0, which was merged into the fyne-cross images last week.
If you can update the images to latest it should be resolved.

**Comment by YinYongTao** [comment]
First of all thank you andydotxyz

I have to say sorry.

I get the code from github Yestoday。

Here is all my docker images

![image](https://user-images.githubusercontent.com/26930834/135266400-644a42c1-428d-4936-bbab-3d167abd6ce8.png)
The error is like above ,so I don't know what can I do

**Comment by andydotxyz** [comment]
Hmm, I see base is up to date, but the android image won't have 2.1 on it yet. @lucor is this a local issue, or are some containers not Fyne v2.1.0 yet?

**Comment by Jacalz** [comment]
I think the updated images are on the develop branch still unless I'm mistaken.

**Comment by lucor** [comment]
@Jacalz was right. I've just pushed the new docker images on docker hub for the v1.1.1 release.
@YinYongTao to use the new image, run:
```
fyne-cross android -pull -app-id=a.b.c 
```

**Comment by YinYongTao** [comment]
First of all thank you @andydotxyz and @lucor 

Still reporting an error

![image](https://user-images.githubusercontent.com/26930834/135372992-202cea41-6f5e-4f9c-b0b2-ccc6e4540d71.png)

![image](https://user-images.githubusercontent.com/26930834/135373112-05f9923d-2b58-4523-977d-ef5f42bb4198.png)

**Comment by lucor** [comment]
@YinYongTao I'm unable to replicate your issue.
I've tested using the following:

- fyne-cross-version

```
fyne-cross version v1.1.0
```

- go.mod
```
module test
go 1.16
require fyne.io/fyne/v2 v2.1.0
```

- main.go
```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(
		container.NewVBox(
			hello,
			widget.NewButton(
				"Hi!",
				func() {
					hello.SetText("Welcome :)")
				},
			),
		),
	)
	w.ShowAndRun()
}
```

- docker images | grep fyne | grep android

```
fyneio/fyne-cross                                                        1.1-android                                                    3fcbfe9c2cba   14 hours ago    6.28GB
```
- fyne-cross android -app-id=a.b.c

```
[i] Target: android
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /code/lucor/test/fyne-cross/bin/android
[✓] "dist" dir cleaned: /code/lucor/test/fyne-cross/dist/android
[✓] "temp" dir cleaned: /code/lucor/test/fyne-cross/tmp/android
[i] Checking for go.mod: /code/lucor/test/go.mod
[✓] go.mod found
[i] Packaging app...
[✓] Package: /code/lucor/test/fyne-cross/dist/android/test.apk
```

Could you please confirm that you still have the issue using the same code / versions above?

If the issue persists, could you please run the command in debug mode with the cache disabled ?
```
fyne-cross android -app-id=a.b.c -no-cache -debug
```
