### ISSUE TITLE
The program built with fyne-cross does not start in Windows

### ISSUE THREAD

**Issue by pereslava** [fyne-io/fyne-cross#7]
Hello.
Just tried to getting started with flyne.
I've package the [Your First App](https://developer.fyne.io/started/firstapp#create-your-first-fyne-app) with flyn-cross.

I've created the package for Windows with (I run it from Ubuntu 18.04)
```
fyne-cross windows -arch=*
```
Result - the Application not starting (32 and 64 bit versions) without error messages and without any loggers.
I tried to run the build in Windows 10.
What I miss?
Could be some runtime have to be installed?

**Comment by pereslava** [comment]
It is similar to [issue on example app](https://github.com/fyne-io/examples/issues/25).
I've tested the build in VirtualBox.
Application is running on real machine with windows.

**Comment by gernotstarke** [comment]
maybe it's too late, but in your VirtualBox VM settings, you need to enable "3D-Acceleration" under the display tab.
