### ISSUE TITLE
Docker Network Bridge Binding Error using systemd-networkd

### ISSUE THREAD

**Issue by Geo25rey** [fyne-io/fyne-cross#8]
I've tried running `fyne-cross` for Windows, Mac, and Linux, but I keep getting this same error:
```
[i] Building binary...
docker: Error response from daemon: failed to create endpoint quirky_mirzakhani on network bridge: failed to add the host (veth241569b) <=> sandbox (vethefcfd83) pair interfaces: operation not supported.
[✗] exit status 125
```

It might be some kind of incompatiblity with systemd-networkd. Was this intented to be run with Network Manager?

Host Information:
```
uname -a
Linux hostname 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
```

```
networkctl --version
systemd 246 (246.6-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by lucor** [comment]
@Geo25rey it could be related to your distro (arch) and docker that to fyne-cross itself.
I don't know if it is your case, but maybe https://github.com/moby/moby/issues/27426 could help?

**Comment by Geo25rey** [comment]
Thanks @lucor I that's it. I just need to restart my computer.
