### ISSUE TITLE
Add support for Windows on arm64

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne-cross#84]
### Is your feature request related to a problem? Please describe:

Windows arm64 laptops are becoming more accessible nowadays and arm specifically is getting very popular. It would be great if we could build binaries for arm64 as well. With Go 1.17, support for this architecture was added so we should at least be halfway to adding this support now. Go 1.18 seems to have a few improvements to the port, so it might not hurt to hold off to that version (not saying that we need, but it might not hurt).

### Is it possible to construct a solution with the existing API?

With the API yes, but I don't know how good the cross-compiling toolchains are from Linux to Windows when 
it comes to arm64. We probably need some research in this space. 

### Describe the solution you'd like to see:

Support for building to Windows on arm64, similar to how we can build for M1 macs or Linux on arm64.

NOTE: No one in our team has an arm64 Windows computer as far as I know. I am opening this mostly so we can add this when the time comes.

**Comment by Jacalz** [comment]
This might actually not be doable. It seems, from https://github.com/hajimehoshi/ebiten/issues/1764, like MinGW doesn’t support ARM.

**Comment by Bluebugs** [comment]
Would using zig solve this too?

**Comment by Jacalz** [comment]
Maybe. I hope so :)

**Comment by lucor** [comment]
Wrt zig: https://github.com/ziglang/zig/issues/9519
