### ISSUE TITLE
Fyne error:  Failed to create dirrectory

### ISSUE THREAD

**Issue by UiP9AV6Y** [fyne-io/fyne-cross#9]
building/packaging for Darwin fails due to the directory hierarchy being partly missing.
the `darwin` [subcommand](https://github.com/fyne-io/fyne-cross/blob/c918ed4d66d6077b2bf06b543857386b7a14ebb1/internal/command/darwin.go#L68) cleans its build environment rather aggressively by [deleting](https://github.com/fyne-io/fyne-cross/blob/c918ed4d66d6077b2bf06b543857386b7a14ebb1/internal/command/command.go#L38) directories recursively and recreating the bases.

during packaging, fyne [fails](https://github.com/fyne-io/fyne/blob/57a948988b31253a47ac5033aefd9b697d82c1e8/cmd/fyne/commands/package-darwin.go#L22) to create its own base directories due to the way fyne-cross mounts the directories

```
[i] Packaging app...
Fyne error:  Failed to create dirrectory
Cause: mkdir /app/fyne-cross/tmp/darwin-amd64/builds/examples/project-01/project-01.app: no such file or directory
At: /go/pkg/mod/fyne.io/fyne@v1.4.2-0.20201125075943-97ad77d2abe0/cmd/f
yne/internal/util/file.go:36
Fyne error:  Failed to create dirrectory
Cause: mkdir /app/fyne-cross/tmp/darwin-amd64/builds/examples/project-01/project-01.app/Contents: no such file or directory
At: /go/pkg/mod/fyne.io/fyne@v1.4.2-0.20201125075943-97ad77d2abe0/cmd/f
yne/internal/util/file.go:36
Failed to write plist template: invalid argument
[✗] could not package the Fyne app: could not package the Fyne app:
exit status 1
```

i wasn't really sure where to create this issue, since packaging with `fyne` locally works just fine.
this issue could as well be fixed in [fyne](https://github.com/fyne-io/fyne/blob/57a948988b31253a47ac5033aefd9b697d82c1e8/cmd/fyne/internal/util/file.go#L34) by creating directories recursively.

**Comment by lucor** [comment]
Could you please re-run the command adding the `-debug` and `-pull` flags and paste the output ?
The `-pull` flag will update the docker image to the latest available that could fix the issue. It update the fyne-cli tool to the latest version (`v1.4.2-0.20201127180716-f9f91c194737`)

**Comment by UiP9AV6Y** [comment]
looking further into the code, i think the problem lies with the `-name` [parameter](https://github.com/fyne-io/fyne-cross/blob/c918ed4d66d6077b2bf06b543857386b7a14ebb1/internal/command/docker.go#L190), which fyne-cross defines as an absolute path (it reuses the output path in its entirety) instead of just a base filename.

**Comment by lucor** [comment]
@UiP9AV6Y good catch. You are right, it is related to the absolute path specified for the fyne-cross's `output` flag.
The objective of that flag is to specify an alternative name for the package. the package will be saved under the fyne-cross/dist folder.
Setting `output` to `project-01` or removing it should allow to compile.

**Comment by UiP9AV6Y** [comment]
can confirm. using a filename without any directories for the `-output` parameter does build and package the app. in my case i simply copied the desired files afterwards from the fyne-cross working directory to the directory i wanted, which is why i specified an absolute in the first place.

**Comment by lucor** [comment]
@UiP9AV6Y the `output` flag has been deprecated in develop in favour of `name`. Additionally a check on the flag has been added to not allow a path for the `output` flag.
I hope that will improve the UX.
Going to close the issue but please feel free to reopen if you have additional feedback.
