### ISSUE TITLE
Ability to build and run mac and ios apps on a NON mac machine

### ISSUE THREAD

**Issue by joeblew99** [fyne-io/fyne-cross#91]
### Describe the solution you'd like to see:

Ability to build and run mac and ios apps on a non mac machine

https://github.com/sickcodes/Docker-OSX works well on Local Linux, Github and Digital Ocean ( as it provides nested virtualisation)

**Comment by andydotxyz** [comment]
You can follow instructions to build for macOS on other computers at https://developer.fyne.io/started/cross-compiling.
Also available is https://github.com/fyne-io/fyne-cross that manages all the development tools for you.

Be aware that Apple licensing does not allow you to build iOS apps on anything other than Apple Mac hardware.
