### ISSUE TITLE
Bug in -tag flag

### ISSUE THREAD

**Issue by luisaodh** [fyne-io/fyne-cross#96]
### Describe the bug:

While compiling, I came across a small discrepancy with the -tag flag.
For compiling I am using the following command:
```fyne-cross linux -arch arm -tags wayland,gles,mesa```
To be able to use this command, I had to use fyne-cross version 1.1.0, because the usage of the version 1.2.0 leads in the error:

[i] Target: linux/arm
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/bin/linux-arm
[✓] "dist" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/dist/linux-arm
[✓] "temp" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/tmp/linux-arm
[i] Checking for go.mod: /home/devel/Dokumente/smart-home/go.mod
[✓] go.mod found
[i] Building binary...
cmd/go: -tags space-separated list contains comma
[✗] exit status 2

But when I display the help menu in the command line (```fyne-cross linux -arch arm --help```) it says for the desription of the -tags: ```List of additional build tags separated by comma.```
Is this meant to be like this or a bug? And how am I supposed to execute my command in version 1.2.0?

**Comment by lucor** [comment]
Fix available for testing in https://github.com/fyne-io/fyne-cross/pull/99

**Comment by Jacalz** [comment]
This will be fixed with the next release. You can test it on the `develop` branch right now if you want.
