### ISSUE TITLE
Add Kubernetes cluster support

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne-cross#98]
### Is your feature request related to a problem? Please describe:

It is possible to setup a cluster of machine that will be able to run multiple containers at the same time or sequentially using Kubernetes based infrastructure. Technically, it should be possible to reuse most of the existing logic in fyne-cross to drive a cluster to do the build work.

### Is it possible to construct a solution with the existing API?

Specifying the cluster is done implicitly with the kubernetes config file. What could be necessary and trigger the switch to use kubernetes could be the specification of a namespace to use with the '-n' parameter usually used by kubectl command.

### Describe the solution you'd like to see:
This is still a reflection and not something where I am sure on how things need to be done.

A little bit of background, kubernetes has an API which orchestrate things in the cluster. This has to use it, but this API is low bandwidth. We shouldn't for example transfer file through it in large quantity. It is ok for debug purpose, but not for production. The container in a kubernetes cluster are named pods. They have ressource attached to them, like filesystem and config. The pods are what fyne-cross should control.

Each machine that form a cluster is named a node and with certain configuration, they can scale on demand too. That's something fyne-cross shouldn't try to control.

You can experiment locally with tool like minikube.

The main difference between podman/docker backend and kubernetes backend is that the container is not going to run on the same machine. Which means all the necessary data must be send over to the container and not rely on the availability of the local file system.

My current idea for that purpose is that all the mounting point are packaged with tar zstd and uploaded to a S3 bucket by fyne-cross. This is usually available has a public front service and can be mimicked with open source solution like min.io. Then the pod during initialization is pointed to that S3 bucket and locally unpack the content. This allow for uploading things once and reusing it potentially for multiple build in a row. Once a build is done, the resulting artifact would also be uploaded to S3. fyne-cross could then download them back on the local machine.

All the configuration for this cloud services are usually stored in environment variable or yaml file. We might start by just supporting environment variable. I will try to build a prototype of this shortly to see how usable it is.

**Comment by metal3d** [comment]
Actually, the best practice is to use CI/CD tools to make this. And Kubernetes can use "Jobs" to make what you expect too but that's not a good practice. I already have made this with Gitlab runners and Drone.io that builds my apps on Kubernetes.
If you really want to use fyne-cross in Kubernetes with one command line, this can be done with a simple sript that launches the needed image in "wait mode" (sleep 3600), then get the corresponding pod, then launching the build command + `kubernetes cp` afterward to get back the result. We made this at work to build training supports while our CI/CI system was not ready.
But, if the need is really important, after decided how to write / get the results, maybe I can take a look (Kubernetes is one of my specialities)

**Comment by Bluebugs** [comment]
This is currently working in develop, if there is bug we should open follow up issue.
